<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonAnSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('mon_ans')->delete();
        $now = Carbon::now();

        DB::table('mon_ans')->insert([
            [
                'id'                     => 1,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Bò',
                'mo_ta'                  => 'Phở bò truyền thống Hà Nội',
                'hinh_anh'               => "https://fohlafood.vn/cdn/shop/articles/bi-quyet-nau-phi-bo-ngon-tuyet-dinh.jpg?v=1712213789",
                'gia_ban'                => 50000,
                'gia_goc'                => 45000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 2,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Gà',
                'mo_ta'                  => 'Phở gà thơm ngon',
                'hinh_anh'               => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuD7uPq_5omNXa_uzoTG8xV0bFQakFLproEQ&s",
                'gia_ban'                => 45000,
                'gia_goc'                => 40000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 3,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Bò',
                'mo_ta'                  => 'Bún bò Huế nóng',
                'hinh_anh'               => "https://static.vinwonders.com/production/bun-bo-hue-ngon-o-sai-gon-1.jpg",
                'gia_ban'                => 55000,
                'gia_goc'                => 50000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 4,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Sườn',
                'mo_ta'                  => 'Cơm tấm sườn nướng',
                'hinh_anh'               => "https://www.huongnghiepaau.com/wp-content/uploads/2017/08/com-tam-suon-bi-cha-chay.jpg",
                'gia_ban'                => 40000,
                'gia_goc'                => 35000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 5,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Thịt',
                'mo_ta'                  => 'Bánh mì pa tê thịt',
                'hinh_anh'               => "https://img.mservice.com.vn/common/u/2e02fb5fe4f64fb55bc713540643c6f8eae702d101cea8c59afc49cfc505fc37/7f4be65d-fab8-4b3e-8883-8a8bfa5bbb08bc5v29pj.jpg",
                'gia_ban'                => 20000,
                'gia_goc'                => 15000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 6,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Mực Nướng',
                'mo_ta'                  => 'Mực tươi nướng than',
                'hinh_anh'               => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7sdGPR8Y11GBqb1ojJtICPCTZU9GhHCOkxg&s",
                'gia_ban'                => 150000,
                'gia_goc'                => 130000,
                'thoi_gian_chuan_bi_phut' => 25,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 7,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Tái',
                'mo_ta'                  => 'Phở bò tái nạm',
                'hinh_anh'               => "https://static.wixstatic.com/media/6e1415_ca315e1833c34abf93d79d7b58a5fe5a~mv2.png/v1/fill/w_670,h_446,al_c,lg_1,q_85,enc_avif,quality_auto/6e1415_ca315e1833c34abf93d79d7b58a5fe5a~mv2.png",
                'gia_ban'                => 55000,
                'gia_goc'                => 50000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 8,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Cá Kho',
                'mo_ta'                  => 'Cơm tấm cá kho tộ',
                'hinh_anh'               => "https://hd1.hotdeal.vn/images/uploads/2016/02/19/233920/233920-com-tam-body-%20%285%29.jpg",
                'gia_ban'                => 45000,
                'gia_goc'                => 40000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 9,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Pâtê',
                'mo_ta'                  => 'Bánh mì pâtê chân không',
                'hinh_anh'               => "https://mms.img.susercontent.com/vn-11134513-7r98o-lv1ikrw2kgs98f@resize_ss1242x600!@crop_w1242_h600_cT",
                'gia_ban'                => 22000,
                'gia_goc'                => 18000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 10,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Tom Hùm Nướng',
                'mo_ta'                  => 'Tôm hùm tươi nướng mỡ hành',
                'hinh_anh'               => "https://cdn.tgdd.vn/2020/07/CookProduct/30-1200x676-3.jpg",
                'gia_ban'                => 250000,
                'gia_goc'                => 220000,
                'thoi_gian_chuan_bi_phut' => 30,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 11,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Chả',
                'mo_ta'                  => 'Bún chả Hà Nội',
                'hinh_anh'               => "https://cooponline.vn/tin-tuc/wp-content/uploads/2025/10/hoc-cach-lam-bun-cha-mien-bac-chuan-ha-noi-tai-nha.png",
                'gia_ban'                => 40000,
                'gia_goc'                => 35000,
                'thoi_gian_chuan_bi_phut' => 12,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 12,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Trứng',
                'mo_ta'                  => 'Cơm tấm chiên trứng',
                'hinh_anh'               => "https://static.vinwonders.com/production/com-tam-da-nang-1.jpg",
                'gia_ban'                => 35000,
                'gia_goc'                => 30000,
                'thoi_gian_chuan_bi_phut' => 8,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 13,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Gà',
                'mo_ta'                  => 'Bánh mì đùi gà xào',
                'hinh_anh'               => "https://cdn2.fptshop.com.vn/unsafe/1920x0/filters:format(webp):quality(75)/banh_mi_ga_xe_2b55e9c8e4.png",
                'gia_ban'                => 25000,
                'gia_goc'                => 20000,
                'thoi_gian_chuan_bi_phut' => 6,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 14,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Cua Hoàng Đế Nướng',
                'mo_ta'                  => 'Cua hoàng đế nướng mỡ hành',
                'hinh_anh'               => "https://i.vietgiaitri.com/2020/10/22/4-buoc-don-gian-che-bien-cua-hoang-de-nuong-pho-mai-thom-ngon-935-5317005.jpg",
                'gia_ban'                => 300000,
                'gia_goc'                => 270000,
                'thoi_gian_chuan_bi_phut' => 35,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 15,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 1,
                'ten_mon_an'             => 'Phở Xương',
                'mo_ta'                  => 'Phở xương bò nấu lâu',
                'hinh_anh'               => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm38K33qOrezi2ZHxXGjJSqDN_G4qKHl7Y7Q&s",
                'gia_ban'                => 60000,
                'gia_goc'                => 55000,
                'thoi_gian_chuan_bi_phut' => 15,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 16,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Gà Hainanese',
                'mo_ta'                  => 'Cơm gà Hainanese chiên',
                'hinh_anh'               => "https://image.foodbook.vn/upload/20250610/1749542026280_blob.jpeg",
                'gia_ban'                => 50000,
                'gia_goc'                => 45000,
                'thoi_gian_chuan_bi_phut' => 18,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 17,
                'id_nha_hang'            => 3,
                'id_danh_muc'            => 4,
                'ten_mon_an'             => 'Bánh Mì Xá Xíu',
                'mo_ta'                  => 'Bánh mì xá xíu mềm',
                'hinh_anh'               => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYQoFUpVy3u4AZb985qu3GxXzLxTrtYJQ1_g&s",
                'gia_ban'                => 23000,
                'gia_goc'                => 19000,
                'thoi_gian_chuan_bi_phut' => 5,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 18,
                'id_nha_hang'            => 4,
                'id_danh_muc'            => 5,
                'ten_mon_an'             => 'Tôm Tươi Nướng',
                'mo_ta'                  => 'Tôm tươi nướng thơm lừng',
                'hinh_anh'               => "https://cdn.mediamart.vn/images/Upload/download/2020-10/1-fH6AM9.jpg",
                'gia_ban'                => 180000,
                'gia_goc'                => 160000,
                'thoi_gian_chuan_bi_phut' => 25,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 19,
                'id_nha_hang'            => 1,
                'id_danh_muc'            => 2,
                'ten_mon_an'             => 'Bún Thang',
                'mo_ta'                  => 'Bún thang Hà Nội',
                'hinh_anh'               => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT88WWwUFLVgE039tbSti6ig4hM8F-HqAXw4Q&s",
                'gia_ban'                => 38000,
                'gia_goc'                => 33000,
                'thoi_gian_chuan_bi_phut' => 11,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'id'                     => 20,
                'id_nha_hang'            => 2,
                'id_danh_muc'            => 3,
                'ten_mon_an'             => 'Cơm Tấm Chả Lụa',
                'mo_ta'                  => 'Cơm tấm chả lụa nấu',
                'hinh_anh'               => "https://vcdn1-giadinh.vnecdn.net/2024/03/07/7Honthinthnhphm1-1709800144-8583-1709800424.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=qHp9T9IgRUv5HEmeMlxkOw",
                'gia_ban'                => 38000,
                'gia_goc'                => 33000,
                'thoi_gian_chuan_bi_phut' => 10,
                'trang_thai'             => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
        ]);
    }
}
